### ISSUE TITLE
Segmentation fault 

### ISSUE THREAD

**Issue by xiaozhuo17** [davidwarne/dx2vtk#2]
Hello,  I am trying to transfer a dx file to vtk file. "Segmentation fault" occured although I changed some parameters in dxFileReader.h.  It was function "memcpy" in code dx2vtk.c that could not run normally in my example.
memcpy(dst,data_array->data,nbytes*data_array->items) .
data_array_>data=37876064 in my case.

Here I upload My dx file. Thanks!
[DX_epicenter.dx.zip]
(https://github.com/davidwarne/dx2vtk/files/3651043/DX_epicenter.dx.zip)

**Comment by davidwarne** [comment]
Hi Xiao Zhou,

I cannot comment on the changes that you have made to dxFileReader.h. I was able to get the current version working with your data file, the Segmentation error is being caused by a buffer overrun that is occurring due to the name of the field object in your data file (I have only supported names of 32 characters)... I renamed the field to "irregular" and it worked fine.

One of the reasons for the 62 byte constraint was to do with the the limit defined legacy VTK format 4.2, where the header in the VTK file cannot be more than 256 bytes.

I will patch the code to make sure this does not cause a crash, but rather just truncate the name.

I attact the VTK file I was able to produce.

Best,
DAvid
[DX_epicenter.zip](https://github.com/davidwarne/dx2vtk/files/3651839/DX_epicenter.zip)

**Comment by xiaozhuo17** [comment]
Hi David,Thanks very much for your help. Do you  mean that you truncate the name of object to “irregular” in line 12 of my dxfile？Zhuo xiao



    


            On 09/25/2019 18:05, David Warne wrote: Hi Xiao Zhou,
I cannot comment on the changes that you have made to dxFileReader.h. I was able to get the current version working with your data file, the Segmentation error is being caused by a buffer overrun that is occurring due to the name of the field object in your data file (I have only supported names of 32 characters)... I renamed the field to "irregular" and it worked fine.
One of the reasons for the 62 byte constraint was to do with the the limit defined legacy VTK format 4.2, where the header in the VTK file cannot be more than 256 bytes.
I will patch the code to make sure this does not cause a crash, but rather just truncate the name.
I attact the VTK file I was able to produce.
Best,
DAvid
DX_epicenter.zip

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/davidwarne/dx2vtk/issues/2?email_source=notifications\u0026email_token=AIN2ZTI6HUE4FMARLEOFGP3QLMZXNA5CNFSM4I2IY272YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7RLHNQ#issuecomment-534950838",
"url": "https://github.com/davidwarne/dx2vtk/issues/2?email_source=notifications\u0026email_token=AIN2ZTI6HUE4FMARLEOFGP3QLMZXNA5CNFSM4I2IY272YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7RLHNQ#issuecomment-534950838",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by davidwarne** [comment]
Yes, thats correct.

I did this by modifying the *.dx file manually in a text editor.

When I get around to it, I will make sure this happens automatically in the dxFileReader.c.

Best,
David

--

Mr David Warne

PhD Candidate  | School of Mathematical Sciences  | Science and Engineering Faculty |

Queensland University of Technology (QUT) | 2 George St, GPO Box 2434, Brisbane 4001 AUSTRALIA |

Mob: +61432800337 | Email: david.warne@qut.edu.au | orcid.org/0000-0002-9225-175X |

ePrints: http://eprints.qut.edu.au/view/person/Warne,_David.html

On Wed, 2019-09-25 at 05:17 -0700, xiaozhuo17 wrote:

Hi David,Thanks very much for your help. Do you  mean that you truncate the name of object to “irregular” in line 12 of my dxfile？Zhuo xiao






On 09/25/2019 18:05, David Warne wrote: Hi Xiao Zhou,
I cannot comment on the changes that you have made to dxFileReader.h. I was able to get the current version working with your data file, the Segmentation error is being caused by a buffer overrun that is occurring due to the name of the field object in your data file (I have only supported names of 32 characters)... I renamed the field to "irregular" and it worked fine.
One of the reasons for the 62 byte constraint was to do with the the limit defined legacy VTK format 4.2, where the header in the VTK file cannot be more than 256 bytes.
I will patch the code to make sure this does not cause a crash, but rather just truncate the name.
I attact the VTK file I was able to produce.
Best,
DAvid
DX_epicenter.zip

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/davidwarne/dx2vtk/issues/2?email_source=notifications\u0026email_token=AIN2ZTI6HUE4FMARLEOFGP3QLMZXNA5CNFSM4I2IY272YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7RLHNQ#issuecomment-534950838",
"url": "https://github.com/davidwarne/dx2vtk/issues/2?email_source=notifications\u0026email_token=AIN2ZTI6HUE4FMARLEOFGP3QLMZXNA5CNFSM4I2IY272YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7RLHNQ#issuecomment-534950838",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
